openapi: 3.0.3
info:
  title: STD23105-TD2
  version: 1.0.0
servers:
  - url: 'https://localhost.std23105.com'
paths:
  /customers:
    get:
      parameters:
        - in: query
          name: page
          required: true
          schema:
            type: integer
        - in: query
          name: pageSize
          required: true
          schema:
            type: integer

      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreateCustomer'

      responses:
        '200':
          description: List of created customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'

    put:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Customer'

      responses:
        '200':
          description: List of modified customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'

    delete:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CustomerIdentifier'

      responses:
        '200':
          description: List of deleted customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'

components:
  schemas:
    Customer:
      allOf:
        - $ref: '#/components/schemas/CustomerIdentifier'
        - $ref: "#/components/schemas/CreateCustomer"
    CreateCustomer:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer

    CustomerIdentifier:
      type: object
      properties:
        id:
          type: string