openapi: 3.0.3
info:
  title: STD23105-TD4
  version: 1.0.0
servers:
  - url: 'https://localhost.std23105.com'
paths:
  /customers/{customerId}/orders:
    get:
      parameters:
        - in : path
          name: customerId
          required: true
          schema:
            type: string
            description: Customer identifier
      responses:
        200:
          description: List of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'

    post:
      parameters:
        - in: path
          name: customerId
          required: true
          schema:
            type: string
            description: Customer identifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/createOrder'

      responses:
        200:
          description: List of new orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'

    put:
      parameters:
        - in: path
          name: customerId
          required: true
          schema:
            type: string
            description: Customer identifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Order'

      responses:
        200:
          description: List of new orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'

components:
  schemas:
    Meal:
      allOf:
        - $ref: '#/components/schemas/MealIdentifier'
        - $ref: "#/components/schemas/CreateMeal"

    CreateMeal:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
          format: float

    MealIdentifier:
      type: object
      properties:
        id:
          type: string

    MealQuantity:
      type: object
      properties:
        quantity:
          type: integer

    OrderIdentifier:
      type: object
      properties:
        id:
          type: string
        reference:
          type: string
        orderDateTime:
          type: string
          format: date-time

    createOrder:
      type: object
      properties:
        meals:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/CreateMeal'
              - $ref: '#/components/schemas/MealQuantity'

    Order:
      allOf:
        - $ref: '#/components/schemas/OrderIdentifier'
        - $ref: '#/components/schemas/createOrder'
